# Generated by Django 5.0.2 on 2024-02-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_admin_user_expense_user_financialreport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
