# Generated by Django 5.0.2 on 2024-03-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password1',
            field=models.CharField(default='12345678', max_length=20),
        ),
    ]
