# Generated by Django 5.0.2 on 2024-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userprofile_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='aaa', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
