# Generated by Django 4.2.11 on 2024-03-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FinancialReport',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
