# Generated by Django 4.2.11 on 2024-03-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_pdfreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfreport',
            name='pdf_file',
        ),
    ]
