# Generated by Django 4.2.11 on 2024-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_pdfreport_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfreport',
            name='pdf_file',
            field=models.BinaryField(default=b''),
        ),
    ]
