# Generated by Django 4.2.11 on 2024-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_report_delete_pdfreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
