# Generated by Django 4.2.11 on 2024-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_expense_amount_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
    ]
